python3: can't open file 'keylogger.py': [Errno 2] No such file or directory
python3: can't open file 'keylogger.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "keylogger.py", line 1, in <module>
    from pynput.keyboard import Key, Listener
  File "/home/ezejoshuannamdi/.local/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/ezejoshuannamdi/.local/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/ezejoshuannamdi/.local/lib/python3.8/site-packages/pynput/_util/__init__.py", line 77, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
